# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52eb14cdf84e090fd9ba1cd65a75b90bfe5d8ee7ffb91099b33c1fe1bfefca87affffa48d833bb62012a8c0b2b421960875417dbeb1b277845007abd963e4bae

test:
  secret_key_base: effde1a1fa92db7aca7772fef3429c9aae0fb70e912c37043365e976ffcfc449990689f264e2bfaee376d7f0185c7d383cb8d14e0f32613df4acf188dd819458

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
